language: perl
matrix:
  include:
    - perl: "5.32"
      dist: xenial
    - perl: "5.28"
      dist: xenial
    - perl: "5.20"
      dist: trusty
    - perl: "5.16"
      dist: trusty
env:
  - "HARNESS_OPTIONS=j6"
install:
  - "cpanm -n Test::Pod Test::Pod::Coverage Data::Validate::Domain Data::Validate::IP YAML::LibYAML"
  - "cpanm -n https://github.com/mojolicious/json-validator/archive/master.tar.gz"
  - "cpanm -n --installdeps ."
notifications:
  email: false
