name: ci-ubuntu
on:
  pull_request:
  push:
    branches:
      - '**'
jobs:
  perl:
    name: "Perl ${{matrix.perl}} on ${{matrix.os}}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl: ["5.32", "5.16"]
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "${{matrix.perl}}"
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: |
          cpanm -n Test::Pod Test::Pod::Coverage Data::Validate::Domain Data::Validate::IP YAML::LibYAML
          cpanm -n https://github.com/mojolicious/json-validator/archive/main.tar.gz
          cpanm -n --installdeps .
      - name: Run tests
        run: prove -l t/*.t
        env:
          HARNESS_OPTIONS: j6
          TEST_POD: 1
