name: ci
on:
  pull_request:
  push:
    branches:
      - "**"
jobs:
  perl:
    name: "Perl ${{matrix.perl}} on ${{matrix.os}}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        perl: ["5.32", "5.26", "5.16"]
    runs-on: "${{matrix.os}}"
    steps:
      - uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "${{matrix.perl}}"
      - run: perl -V
      - name: Fix ExtUtils::MakeMaker for Perl 5.16
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install dependencies
        run: |
          cpanm -n Test::CPAN::Changes Test::Pod::Coverage Test::Pod Test::Spelling
          cpanm -n Data::Validate::Domain Data::Validate::IP YAML::LibYAML
          cpanm -n https://github.com/mojolicious/json-validator/archive/main.tar.gz
          cpanm -n --installdeps .
      - name: Run tests
        run: prove -l t/*.t
        env:
          HARNESS_OPTIONS: j4
